INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('uzatilmissarjor', 'Uzatılmış Sarjör', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('namluucu', 'Namlu Ucu', -1, 0, 1); 
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('mk2tabdurbun', 'MK2 Tab. Dürbünü', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('goldskin', 'Altın Skin', -1, 0, 1); 
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('tufekdurbun', 'Tüfek Dürbünü', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('vipskinbutterfly', 'VIP Skin Butterfly', -1, 0, 1); 
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskinlove', 'Knuckle Skin LOVE', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('ortadurbun', 'Orta Dürbün', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('uzundurbun', 'Uzun Dürbün', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('holografik', 'Holografik Dürbün', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('platin50', 'Platin Pistol 50 Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('woodheavyp', 'Wood Heavy Pistol Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('woodrifleskin', 'Wood Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skullrifleskin', 'Skull Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('zebrarifleskin', 'Zebra Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('boomrifleskin', 'Boom Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('taktikselnamlufreni', 'Taktiksel Namlu Freni', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskinpimp', 'Knuckle Skin PIMP', -1, 0, 1); 
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskinballas', 'Knuckle Skin Ballas', -1, 0, 1); 
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskindollar', 'Knuckle Skin Dollar', -1, 0, 1); 
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskindiamond', 'Knuckle Skin Diamond', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskinhate', 'Knuckle Skin Hate', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskinplayer', 'Knuckle Skin Player', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('knuckleskinvagos', 'Knuckle Skin Vagos', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('silahfeneri', 'Silah Feneri', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('susturucu', 'Susturucu', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('grip', 'Grip', -1, 0, 1);